stages: # List of stages for jobs, and their order of execution
  - build
  - deploy

image: node

#cache:
#  paths:
#    - node_modules/

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - test -d ~/.ssh || mkdir -p 0700 ~/.ssh
  - grep -Fq 	94.250.250.194 ~/.ssh/known_hosts || ssh-keyscan -t rsa 	94.250.250.194 >> ~/.ssh/known_hosts
  - mv $SSH_PRIVATE_KEY ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo "Start building"

  #- yarn

deploy:
  stage: deploy
  environment:
    name: production
    url: 94.250.250.194
  script:
    - bash deploy/deploy.sh
  only:
    - main
